on: 
  - push
      with:
        paths: [README.md]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo "$GITHUB_CONTEXT"
